spring:
  data:
    cassandra:
      username: your-username
      password: your-password
      keyspace-name: "squint"
      cloud:
        secure-connect-bundle: ../../..//../secure-connect-squint.zip