spring:
  logging:
    level:
      org.springframework: DEBUG
  application:
    name: Squint
  data:
    cassandra:
      keyspace-name: squint
      username: oXWQeXPabwZfWjuAtQrajYZG
      password: MAm_9kjPHOnnGKQB93+YwOf2P+Ni.SEmjR1pPXYUrgw9oRPA.ev5zwoXE.+YFY4ke,Hf+PRirlgkRJ2IS,gZnZmZ9kpdhzZ9ldhFcDkNXjNehFTvPHK5sIXujGcc2Cbl
      schema-action: create-if-not-exists
      request:
        timeout: 30s
      connection:
        connect-timeout: 30s
        init-query-timeout: 30s

  datastax.astra:
    secure-connect-bundle: secure-connect.zip


  astra.db:
    id: 68d7f79c-a209-4ea7-969a-215f6973eeaf
    region: us-east1
    keyspace: squint
    application.token: AstraCS:377773f1c4c7f0e67d769e0284416d0e3cab375689f2922fce59ee20cef2bfbf