spring:
  data:
    cassandra:
      keyspace-name: my_keyspace
      contact-points: your_datastax_astra_contact_points
      port: your_port
      username: your_username
      password: your_password
      ssl: true