spring:
  data:
    cassandra:
      keyspace-name: "squint"
      username: your-username
      password: your-password
      cloud:
        secure-connect-bundle: ../../../../secure-connect-squint.zip